config/routes.rb
Rails.application.routes.draw do
  # all joomla going now outside
  # was started from the beginning with a direct URL, e.g. "joomla" instead "start/joomla"
  get 'joomla'               => redirect(QUOTE_JOOMLA_WIKI[:de])
  get 'de/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:de])
  get 'joomla_english'       => redirect(QUOTE_JOOMLA_WIKI[:en]) # used from Joomla module, version 1.4
  get 'start/joomla_english' => redirect(QUOTE_JOOMLA_WIKI[:en]) # old page link before I18n
  get 'en/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:en])
  get 'es/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:es])
  get 'ja/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:ja])
  get 'uk/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:uk])

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: "static_pages#list"

    # static_pages controller with historical and nicer 'start' URL
    get 'start/humans'  => 'static_pages#humans'
    get 'start/contact' => 'static_pages#contact'
    get 'start/project' => 'static_pages#project'
    get 'start/use'     => 'static_pages#use'
    get 'start/help'    => 'static_pages#help'
    get 'start/list'    => 'static_pages#list'

    # dynamic generated humans.txt
    get "humans.txt" => "static_pages#humans"

    get  'categories/list_no_public'              => 'categories#list_no_public'
    get  'categories/list_by_letter/:letter'      => 'categories#list_by_letter'
    get  'categories/list_duplicates'             => 'categories#list_duplicates'
    get  'authors/list_no_public'                 => 'authors#list_no_public'
    get  'authors/list_by_letter/:letter'         => 'authors#list_by_letter'
    get  'quotations/list_no_public'              => 'quotations#list_no_public'
    get  'quotations/list_by_user/:user'          => 'quotations#list_by_user'
    get  'quotations/list_by_category/:category'  => 'quotations#list_by_category'
    get  'quotations/list_by_author/:author'      => 'quotations#list_by_author'
    post 'quotations/search_author'               => 'quotations#search_author'
    get  'quotations/author_selected/:author_id'  => 'quotations#author_selected'
    get  'quotations/category_selected/:ids'      => 'quotations#category_selected'
    get  'quotations/delete_category/(:ids)'      => 'quotations#delete_category'
    get  'comments/list_by_user/:user'            => 'comments#list_by_user'

    # Hotwire Stimulus & Hotwire Turbo
    get  'users/show_avatar'                      => 'users#show_avatar'
    get  'users/recreate_avatar'                  => 'users#recreate_avatar'
    get  'users/take_gravatar'                    => 'users#take_gravatar'
    post 'users/upload_avatar'                    => 'users#upload_avatar'

    # default controller routes
    resources :authors, :categories, :quotations
    resources :users, except: [:show, :destroy]
    resources :user_sessions, except: [:index, :show, :edit, :update]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]

    get "login"  => "user_sessions#new"
    get "logout" => "user_sessions#destroy"

    get "forbidden" => "static_pages#forbidden"
    get "not_found" => "static_pages#not_found"

    # see https://www.mintbit.com/blog/custom-404-500-error-pages-in-rails
    get "/400" => "static_pages#bad_request"
    get "/404" => "static_pages#not_found"
    get "/500" => "static_pages#internal_server"
    get "/422" => "static_pages#unprocessable"

    # catch all
    match "*path" => "static_pages#catch_all", via: :all
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  validates :comment, presence: true, length: { maximum: 512 }

  def self.number_of(o)
    where(commentable_type: o.class.to_s, commentable_id: o.id).count
  end

  def self.count_users_comments(user_id)
    Comment.where(user_id: user_id).count
  end

  def editable_by(user)
    user && user.id && ((user.id == self.user_id) || user.admin)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::Helpers::TextHelper # for truncate()
  before_action :set_comment, only: [:edit, :update, :destroy]

  # GET /comments only for admins
  def index
    if !current_user or current_user.admin == false
      flash[:error] = t("g.no_admin")
      render "static_pages/forbidden", status: :forbidden
      return false
    end
    @comments = Comment.paginate_by_sql "select * from comments order by updated_at desc", :page => params[:page],
                                                                                           :per_page => 10
    # check pagination second time with number of pages
    bad_pagination?(@comments.total_pages)
  end

  # POST /comments/new
  def create
    return unless logged_in? t("comments.login_missing")

    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @commentable_type = @comment.commentable_type
    @commentable_id = @comment.commentable_id
    @comments = Comment.where(commentable_type: @commentable_type, commentable_id: @commentable_id)

    respond_to do |format|
      if @comment.save
        format.turbo_stream
        format.html {
          redirect_to controller: @commentable_type.downcase.pluralize, action: "show", locale: I18n.locale,
                      id: @commentable_id
        }
      else
        if @comment.errors.any?
          error = t("g.error", count: @comment.errors.count)
          @comment.errors.each do |message|
            error << ". #{message.full_message}!"
          end
        end
        logger.error "comment.save FAILED with #{error}"
        format.turbo_stream
        format.html {
          flash[:error] = error
          redirect_to controller: @commentable_type.downcase.pluralize, action: "show", locale: I18n.locale,
                      id: @commentable_id, status: :unprocessable_content
        }
      end
    end
  end

  # GET /comments/1/edit only for admin or own user
  def edit
    return unless access?(:update, @comment)
  end

  # PATCH /comments/1
  def update
    return unless access?(:update, @comment)

    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("comment", partial: "comments/comments_table") }
        format.html {
          redirect_to controller: @commentable_type.downcase.pluralize, action: "show", locale: I18n.locale,
                      id: @commentable_id, notice: "comment was successfully updated."
        }
      else
        format.html { render :edit, status: :unprocessable_content }
      end
    end
  end

  # DELETE /comments/1
  def destroy
    return unless access?(:destroy, @comment)

    respond_to do |format|
      if @comment.destroy
        @comments.reload
        format.turbo_stream { render turbo_stream: turbo_stream.replace("comment", partial: "comments/comments_table") }
        format.html {
          redirect_to controller: @commentable_type.downcase.pluralize,
                      action: "show",
                      locale: I18n.locale,
                      id: @commentable_id,
                      notice: t("comments.deleted", comment: truncate(@comment.comment, length: 20))
        }
      else
        format.html { render :edit, status: :unprocessable_content }
      end
    end
  end

  # list comments created by a user ID
  # e.g. GET /quotations/list_by_user/1
  #      GET /quotations/list_by_user/1?page=42
  # it is free to be called w/o login, but actual it is only linked from admin view
  def list_by_user
    user_id = my_sql_sanitize(params[:user])

    unless User.exists?(id: user_id)
      flash[:error] = t("g.missing_user", user: params[:user])
      return redirect_to root_url
    end

    @comments = Comment.where(user_id: user_id).order(created_at: :desc)

    @comments = @comments.paginate(page: params[:page], per_page: PER_PAGE)
    # check pagination second time with number of pages
    bad_pagination?(@comments.total_pages)
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
    @commentable_type = @comment.commentable_type
    @commentable_id = @comment.commentable_id
    @comments = Comment.where(commentable_type: @comment.commentable_type, commentable_id: @comment.commentable_id)
    logger.debug { "set_comment: id=#{params[:id]}, @comment=#{@comment.inspect}, @comments.count=#{@comments.count}" }
  rescue
    flash[:error] = t("comments.id_does_not_exist", id: params[:id])
    render "static_pages/not_found", status: :not_found
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:comment, :locale, :commentable_type, :commentable_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def image_tag_for_commentable_type(comment)
    if comment.commentable_type == "Category"
      return image_tag "category.png", alt: t("g.category_alt"), title: t("g.category")
    elsif comment.commentable_type == "Author"
      return image_tag "author.png", alt: t("g.author_alt"), title: t("g.author")
    end

    # else "Quotation"
    image_tag "zitat-service.svg", alt: t("g.quote_alt"), title: t("g.quote"), id: 'logo16'
  end
end

app/views/comments/_comments_table.html.erb
<%= turbo_frame_tag :comment do %>
  <% if @comments&.any? %>
    <div class="table" id="comments">
      <div class="tdata">
        <% @comments.each do |comment|
            border_bottom_is_not_last = comment == @comments.last ? "" : "border-bottom"
            header = image_tag("#{AVATARS_URL}/#{comment.user_id}.png", class: "avatar-small")
            header << raw(' <span class="opacity-50 font-size-smaller">')
            header << hu(comment.user_id)
            if comment.updated_at && comment.created_at
              # i18n-tasks health counts them as unused, therefor name them explicit
              # i18n-tasks-use t('comments.commented_on')
              # i18n-tasks-use t('comments.updated_at')
              header << raw("<span class=\"opacity-50  font-size-smaller\"> #{t("comments.commented_on")} ")
              header << nice_date(comment.created_at)
              if comment.updated_at != comment.created_at
                header << "; #{t("comments.updated_at")} "
                header << nice_date(comment.updated_at)
              end
              header << raw("</span>")
            end
          %>
            <div class="table-row-group" id="<%= "#{dom_id(comment)}_container" %>">
              <div class="tr <%= "#{dom_id(comment)}_tr" %>">
                <div class="td"><%= raw(header) %></div>
                <div class="td">
                  <div class="float-right">
                    <%# having pencil-button, delete-button and flag inline in one line %>
                    <div class="inline-elements">
                      <% if comment.editable_by(current_user) %>
                        <%= link_to image_tag("pencil.png", class: "edit_comment", alt: t("g.pencil"), title: t("g.update")),
                          { locale: I18n.locale, action: :edit, controller: :comments, id: comment },
                          data: {
                            turbo_frame: dom_id(comment)
                          },
                          class: "no-decoration" %>
                        <%= link_to image_tag("cancel.png", alt: t("g.red_cross"), title: t("g.delete")),
                          { locale: I18n.locale, action: :destroy, controller: :comments, id: comment },
                          method: :delete,
                          data: {
                            turbo_method: :delete,
                            turbo_confirm: t("comments.delete", comment: truncate(comment.comment, length: 20))
                          },
                          class: "no-decoration" %>
                      <% end %>
                      <div class="opacity-50"><%= raw "#{string_for_locale(comment.locale)}</span>" %></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="tr <%= "#{dom_id(comment)}_tr #{border_bottom_is_not_last}" %>">
                <%= turbo_frame_tag "#{dom_id(comment)}" do %>
                  <div id="<%= "#{dom_id(comment)}" %>" class="td"><%= raw transformLink(comment.comment) %></div>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/_list_content.erb
<!-- @formatter:off -->
<%= will_paginate @comments %>

<table class="border">

  <tr>
    <th><%= t("g.link") %></th>
    <th><%= t("g.date") %></th>
    <th><%= t("g.user") %></th>
    <th><%= t("g.comment", count: 1) %></th>
    <th><%= t("g.locale") %></th>
  </tr>

  <%
    odd_or_even = 0
    for comment in @comments
      odd_or_even = 1 - odd_or_even
      dates = nice_date(comment.created_at)
      dates = nice_date(comment.updated_at) if comment.updated_at and comment.created_at and comment.updated_at > comment.created_at
  %>
      <tr valign="top" class="ListLine<%= odd_or_even %>">
        <td><%= link_to raw("#{image_tag_for_commentable_type(comment)} #{comment.commentable_id}"), locale: I18n.locale,
          controller: comment.commentable_type.pluralize.downcase, action: "show", id: comment.commentable_id %></td>
        <td><%= raw dates %></td>
        <td><%= image_tag("#{AVATARS_URL}/#{comment.user_id}.png", class: "avatar-small") + " " + 
                hu(comment.user_id) %></td>
        <td><%= raw transformLink(comment.comment) %></td>
        <td><%= raw string_for_locale(comment.locale, true) %></td>
      </tr>
    <% end %>

</table>

app/views/comments/_new.html.erb
<% if current_user %>

  <%= form_tag(url_for(controller: :comments, action: :create, locale: I18n.locale), id: 'new_comment_form') do |form| %>

    <% if @comment and @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= t("g.error", count: @comment.errors.count) %></h2>
        <ul>
          <% @comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= text_field_tag 'comment[comment]', nil, size: 80, maxlength: 512, oninput: 'myUpdateCommentCountdown("comment_comment", 512)' %>
    <span id="comment_comment_countdown" class="countdown opacity-50 font-size-smaller"> </span>
    <%= hidden_field_tag 'comment[commentable_type]', @commentable_type %>
    <%= hidden_field_tag 'comment[commentable_id]', @commentable_id %>
    <%= hidden_field_tag 'comment[locale]', I18n.locale %>
    <%= submit_tag t("g.add") %>
    <p class="opacity-50 font-size-smaller"><%= raw t("comments.rules", link: link_to(t("comments.guidelines"), start_help_path(locale: I18n.locale, anchor: "comments"))) %></p>
  <% end %>
<% else %>
  <p class="opacity-50 font-size-smaller"><%= raw t("comments.needs_login", login_link: link_to(t('layouts.application.login'), login_path(locale: I18n.locale))) %></p>
<% end %>

app/views/comments/_show.html.erb
<h2><%= t("g.comment", count: 2) %></h2>

<%= render partial: "comments/comments_table" %>

<%= render partial: "comments/new" %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.replace "comment" do %>
  <%= render partial: "comments/comments_table" %>
<% end %>
<%= turbo_stream.replace "new_comment_form" do %>
  <%= render partial: "comments/new" %>
<% end %>
<%= turbo_stream.before "comment" do %>
  <%# used to set focus on input field after turbo replace %>
  <%= javascript_tag 'myCleanField("comment_comment")' %>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag dom_id(@comment) do %>
  <% if @comment and @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("g.error", count: @comment.errors.count) %></h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_tag(url_for(controller: :comments, action: :update, locale: I18n.locale), method: :patch) do |form| %>
    <%= text_field_tag 'comment[comment]', @comment.comment, id: 'edit_comment', size: 80, maxlength: 512, onfocus: 'myUpdateCommentCountdown("edit_comment", 512)', oninput: 'myUpdateCommentCountdown("edit_comment", 512)', autofocus: true %>
    <%= hidden_field_tag 'comment[locale]', I18n.locale %>
    <span id="edit_comment_countdown" class="countdown opacity-50 font-size-smaller"> </span>
    <%=
        link_to image_tag("arrow_undo.png",
          alt: t("g.arrow_undo_alt"), title: t("g.cancel")),
          url_for(controller: @commentable_type.downcase.pluralize, action: :show, id: @commentable_id),
          class: 'not_dashed'
    %>
    <%= submit_tag t("g.update") %>
  <% end %>
  <%= javascript_tag 'myMoveCursorToEnd("edit_comment")' %>
<% end %>

app/views/comments/index.html.erb
<h1><%= "#{number_with_delimiter(@comments.total_entries)} #{t("g.comment", count: @comments.total_entries)}" %></h1>

<%= render 'list_content' %>

app/views/comments/list_by_user.html.erb
<h1><%= "#{number_with_delimiter(@comments.total_entries)}
         #{t('g.comment', count: @comments.total_entries)}
         #{t("g.of_the_user", user: hu(params[:user]))}" %>
    <%= image_tag("#{AVATARS_URL}/#{params[:user]}.png", class: "avatar") %></h1>

<%= render 'list_content' %>