config/routes.rb
Rails.application.routes.draw do
  # all joomla going now outside
  # was started from the beginning with a direct URL, e.g. "joomla" instead "start/joomla"
  get 'joomla'               => redirect(QUOTE_JOOMLA_WIKI[:de])
  get 'de/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:de])
  get 'joomla_english'       => redirect(QUOTE_JOOMLA_WIKI[:en]) # used from Joomla module, version 1.4
  get 'start/joomla_english' => redirect(QUOTE_JOOMLA_WIKI[:en]) # old page link before I18n
  get 'en/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:en])
  get 'es/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:es])
  get 'ja/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:ja])
  get 'uk/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:uk])

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: "static_pages#list"

    # static_pages controller with historical and nicer 'start' URL
    get 'start/humans'  => 'static_pages#humans'
    get 'start/contact' => 'static_pages#contact'
    get 'start/project' => 'static_pages#project'
    get 'start/use'     => 'static_pages#use'
    get 'start/help'    => 'static_pages#help'
    get 'start/list'    => 'static_pages#list'

    # dynamic generated humans.txt
    get "humans.txt" => "static_pages#humans"

    get  'categories/list_no_public'              => 'categories#list_no_public'
    get  'categories/list_by_letter/:letter'      => 'categories#list_by_letter'
    get  'categories/list_duplicates'             => 'categories#list_duplicates'
    get  'authors/list_no_public'                 => 'authors#list_no_public'
    get  'authors/list_by_letter/:letter'         => 'authors#list_by_letter'
    get  'quotations/list_no_public'              => 'quotations#list_no_public'
    get  'quotations/list_by_user/:user'          => 'quotations#list_by_user'
    get  'quotations/list_by_category/:category'  => 'quotations#list_by_category'
    get  'quotations/list_by_author/:author'      => 'quotations#list_by_author'
    post 'quotations/search_author'               => 'quotations#search_author'
    get  'quotations/author_selected/:author_id'  => 'quotations#author_selected'
    get  'quotations/category_selected/:ids'      => 'quotations#category_selected'
    get  'quotations/delete_category/(:ids)'      => 'quotations#delete_category'
    get  'comments/list_by_user/:user'            => 'comments#list_by_user'

    # Hotwire Stimulus & Hotwire Turbo
    get  'users/show_avatar'                      => 'users#show_avatar'
    get  'users/recreate_avatar'                  => 'users#recreate_avatar'
    get  'users/take_gravatar'                    => 'users#take_gravatar'
    post 'users/upload_avatar'                    => 'users#upload_avatar'

    # default controller routes
    resources :authors, :categories, :quotations
    resources :users, except: [:show, :destroy]
    resources :user_sessions, except: [:index, :show, :edit, :update]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]

    get "login"  => "user_sessions#new"
    get "logout" => "user_sessions#destroy"

    get "forbidden" => "static_pages#forbidden"
    get "not_found" => "static_pages#not_found"

    # see https://www.mintbit.com/blog/custom-404-500-error-pages-in-rails
    get "/400" => "static_pages#bad_request"
    get "/404" => "static_pages#not_found"
    get "/500" => "static_pages#internal_server"
    get "/422" => "static_pages#unprocessable"

    # catch all
    match "*path" => "static_pages#catch_all", via: :all
  end
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :user
  belongs_to :author
  has_and_belongs_to_many :categories
  has_many :comments, as: :commentable
  before_validation :convert_empty_strings_to_nil
  before_destroy :check_comments
  validates :quotation, presence: true, length: { maximum: 512 }, uniqueness: { case_sensitive: false }
  validates :source, presence: false, length: { maximum: 255 }, uniqueness: false
  validates :source_link, presence: false, length: { maximum: 255 }, uniqueness: false
  validates :locale, presence: true

  # count all non-public quotes
  def self.count_non_public
    return count_by_sql("select count(*) from quotations where public = 0")
  end

  def self.count_users_quotations(user_id)
    Quotation.where(user_id: user_id).count
  end

  def get_author_name_or_blank
    self.author ? self.author.get_author_name_or_blank : ""
  end

  # returns authors name and source name or blank
  # returns "", "authors name", "source" or "authors name, source"
  #
  def get_author_and_source_name
    ret = get_author_name_or_blank
    ret += ", " unless ret.blank? or self.source.blank?
    ret += self.source unless self.source.blank?
    ret
  end

  # returns list of quotations
  # can be reduced by pattern or by locales
  # sorted by created_at
  def self.search_by_pattern_and_locales(pattern, locales)
    if pattern.present?
      quotations = where("quotation LIKE ?", "%#{pattern}%").order(created_at: :desc)
    else
      quotations = all.order(created_at: :desc)
    end
    quotations = quotations.where(locale: locales) if locales.present?
    quotations
  end

  # returns list of quotations of the given author ID and
  # can be reduced by locales
  # sorted by created_at
  def self.by_author_and_locales(author_id, locales = nil)
    quotations = where(author_id: author_id).order(created_at: :desc)
    quotations = quotations.where(locale: locales) if locales.present?
    quotations
  end

  # returns list of quotations of the given category ID and
  # can be reduced by locales
  # sorted by created_at
  def self.by_category_and_locales(category_id, locales = nil)
    quotations = joins(:categories).where(categories: { id: category_id }).distinct.order(created_at: :desc)
    quotations = quotations.where(locale: locales) if locales.present?
    quotations
  end

  # returns list of non-public quotations and
  # can be reduced by locales
  # sorted by created_at
  def self.not_public_and_by_locales(locales = nil)
    quotations = where(public: 0).order(created_at: :desc)
    quotations = quotations.where(locale: locales) if locales.present?
    quotations
  end

  private

  # source and source_link are optional and saved as NULL in database if blank
  def convert_empty_strings_to_nil
    self.source      = nil if self.source.blank?
    self.source_link = nil if self.source_link.blank?
  end

  # don't delete quotes with comments
  def check_comments
    if comments.any?
      errors.add :base, :has_comments
      throw :abort
    end
  end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  include ActionView::Helpers::TextHelper # for truncate()
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  before_action :category_ids_param_to_array
  before_action :set_comments, only: [:show, :destroy]

  # list quotations
  # with the ability to reduce the list by search pattern or if locales are given
  # e.g. GET /quotations
  #      GET /quotations?pattern=berlin
  #      GET /quotations?page=42
  #      GET /quotations?locales=uk,es
  def index
    # use current locale as default if param locales is not set
    params[:locales] ||= I18n.locale.to_s

    @quotations = Quotation.search_by_pattern_and_locales(params[:pattern], split_params_locales)
                           .paginate(page: params[:page], per_page: QUOTES_PER_PAGE)

    # check pagination second time with number of pages
    bad_pagination?(@quotations.total_pages)

    # give hint on first page if no other notice exist
    if !flash[:notice] and (!params[:page] or params[:page].to_i == 1)
      flash.now[:notice] = t(".order")
    end
  end

  # GET /quotations/1
  def show
  end

  # GET /quotations/new
  def new
    return unless logged_in? t("quotations.login_missing")

    @quotation = Quotation.new(user_id: current_user.id, locale: I18n.locale)
  end

  # GET /quotations/1/edit
  def edit
    return unless access?(:update, @quotation)
  end

  # GET quotations/author_selected/author_id
  # called from search author result list as a click on a link
  def author_selected
    return unless logged_in? t("quotations.login_missing")

    turbo_author(nil, params[:author_id])
    render turbo_stream: turbo_stream_do_actions
  end

  # GET quotations/category_selected/327,139,42-44,45
  # called from search category result list as a click on a link
  # with all choosen categories left and all recommended categories right from minus separator
  # first entry in the choosen categories list is the new selected category
  def category_selected
    return unless logged_in? t("quotations.login_missing")

    category_ids = split_two_id_arrays(params[:ids], 0)
    category_id = category_ids[0]
    rec_ids = split_two_id_arrays(params[:ids], 1)
    logger.debug {
      "category_selected() category_id=#{nol(category_id)} " +
        "category_ids=#{nol(category_ids, true)} rec_ids=#{nol(rec_ids, true)}"
    }
    turbo_category(category_id, category_ids, rec_ids)
    render turbo_stream: turbo_stream_do_actions
  end

  # GET quotations/delete_category/305,487-44,45
  # called from each collected category to delete
  # only remaining categories are given in the list, left from minus separator
  # list of remaining categories is empty in case the last category is to delete
  # right from minus separator is the list of recommended categories
  def delete_category
    return unless logged_in? t("quotations.login_missing")

    category_ids = split_two_id_arrays(params[:ids], 0)
    rec_ids = split_two_id_arrays(params[:ids], 1)
    logger.debug { "delete_category() category_ids=#{nol(category_ids, true)} rec_ids=#{nol(rec_ids, true)}" }
    turbo_category(nil, category_ids, rec_ids)
    render turbo_stream: turbo_stream_do_actions
  end

  # POST /quotations
  def create
    return unless logged_in? t("quotations.login_missing")

    # set @authors and @categories from autocompletion fields and return hidden fields authors ID and category IDs
    author_id, category_ids = scan_params_for_create_or_update

    if params[:commit]
      @quotation = Quotation.new(quotation_params)
      # set https if needed and possible and follow redirects, if not reachable set flash[:warning]
      verify_and_improve_link

      @quotation.user_id = current_user.id
      @quotation.author_id = 0 unless @quotation.author_id # empty author field is an unknown author, which has id 0
      logger.debug { "saving #{@quotation.inspect}" }
      if @quotation.save
        hint = t(".created", id: @quotation.id)
        # give hint, e.g. if author autocomplete field is empty and unknown author is used
        hint << " #{t(".author_used", author: Author.find(@quotation.author_id).name)}" if @authors.count != 1
        return redirect_to quotation_path(@quotation, locale: I18n.locale), notice: hint
      else
        render :new, status: :unprocessable_content
      end
    else
      turbo_author(author_id)
      turbo_category(nil, category_ids, Category.check(params[:quotation][:quotation]))
      render turbo_stream: turbo_stream_do_actions
    end
  rescue Exception => exc
    problem = "#{exc.class} #{exc.message}"
    logger.error "create quotation failed: #{problem}"
    flash[:error] = t(".failed", exception: problem)
    render :new, status: :unprocessable_content
  end

  # PATCH/PUT /quotations/1
  def update
    return unless access?(:update, @quotation)

    # set @authors and @categories from autocompletion fields and return hidden fields authors ID and category IDs
    author_id, category_ids = scan_params_for_create_or_update

    if params[:commit]
      # Are associated categories changed? Compare from params with existing list by hand as changed?
      # does not exist for has_and_belongs_to_many.
      categories_changed = category_ids.sort != @quotation.category_ids.sort
      @quotation.assign_attributes(quotation_params)
      # set https if needed and possible and follow redirects, if not reachable set flash[:warning]
      verify_and_improve_link

      logger.debug { "update() categories_changed=#{categories_changed}, quotation.changed #{@quotation.changes}" }
      if @quotation.changed? or categories_changed
        if @quotation.save
          # set Quotation.updated_at even if there are changes in associated categories
          @quotation.touch if categories_changed
          hint = t(".updated")
          # give hint, e.g. if author autocomplete field is not completed
          hint << " #{t(".author_unchanged", author: Author.find(@quotation.author_id).name)}" if @authors.count != 1
          return redirect_to quotation_path(@quotation, locale: I18n.locale), notice: hint
        else
          render :edit, status: :unprocessable_content
        end
      else # quotation and associated categories are unchanged
        hint = t(".unchanged")
        # give hint, e.g. if author autocomplete field is not completed
        hint << " #{t(".author_unchanged", author: Author.find(@quotation.author_id).name)}" if @authors.count != 1
        return redirect_to @quotation, notice: hint
      end
    else
      turbo_author(author_id)
      turbo_category(nil, category_ids, Category.check(@quotation))
      render turbo_stream: turbo_stream_do_actions
    end
  end

  # DELETE /quotations/1
  def destroy
    return unless access?(:destroy, @quotation)

    if @quotation.destroy
      flash[:notice] = e = t(".deleted", quote: truncate(@quotation.quotation, length: 20))
      logger.debug { "destroyed quotation ID=#{@quotation.id} – #{e}" }
      redirect_to quotations_url
    else
      flash[:error] = e = @quotation.errors.any? ? @quotation.errors.first.full_message : "error"
      logger.error "destroy quotation ID=#{@quotation.id} – failed with #{e}"
      render :show, status: :unprocessable_content
    end
  end

  # list quotations created by a user ID
  # with the ability to reduce the list if locales are given
  # e.g. GET /quotations/list_by_user/1
  #      GET /quotations/list_by_user/1?page=42
  #      GET /quotations/list_by_user/1?locales=uk,es
  def list_by_user
    user_id = my_sql_sanitize(params[:user])

    unless User.exists?(id: user_id)
      flash[:error] = t("g.missing_user", user: params[:user])
      return redirect_to root_url
    end

    locales = split_params_locales

    @quotations = Quotation.where(user_id: user_id)
                           .order(created_at: :desc)

    @quotations = @quotations.where(locale: locales) if locales.present?

    @quotations = @quotations.paginate(page: params[:page], per_page: QUOTES_PER_PAGE)
    # check pagination second time with number of pages
    bad_pagination?(@quotations.total_pages)
  end

  # list quotations by catgegory ID
  # with the ability to reduce the list if locales are given
  # e.g. GET /quotations/list_by_category/1
  #      GET /quotations/list_by_category/1?page=42
  #      GET /quotations/list_by_category/1?locales=uk,es
  def list_by_category
    category_id = params[:category]
    unless @category = Category.find_by(id: category_id)
      flash[:error] = t(".no_category", id: category_id)
      return redirect_to root_url
    end

    @quotations = Quotation.by_category_and_locales(category_id, split_params_locales)
                           .paginate(page: params[:page], per_page: QUOTES_PER_PAGE)

    # check pagination second time with number of pages
    bad_pagination?(@quotations.total_pages)
  end

  # list quotations by author ID
  # with the ability to reduce the list if locales are given
  # e.g. GET /quotations/list_by_author/1
  #      GET /quotations/list_by_author/1?page=42
  #      GET /quotations/list_by_author/1?locales=uk,es
  def list_by_author
    author_id = params[:author]

    unless @author = Author.find_by(id: author_id)
      flash[:error] = t(".no_author", id: author_id)
      return redirect_to root_url
    end

    @quotations = Quotation.by_author_and_locales(author_id, split_params_locales)
                           .paginate(page: params[:page], per_page: QUOTES_PER_PAGE)

    # check pagination second time with number of pages
    bad_pagination?(@quotations.total_pages)
  end

  # for admins list all not public categories
  # with the ability to reduce the list if locales are given
  def list_no_public
    return unless access?(:admin, Quotation.new)

    locales = split_params_locales
    @quotations = Quotation.not_public_and_by_locales(locales)
                           .paginate(page: params[:page], per_page: QUOTES_PER_PAGE)

app/helpers/quotations_helper.rb
module QuotationsHelper
  # returns - with links if exist - authors name and quotations source name or blank
  # returns "", "authors name", "source" or "authors name, source"
  # ignore author.id == 0 "unknown"
  #
  def get_linked_author_and_source(quote)
    my_source = quote.source
    if quote.source.present? && quote.source_link.present?
      my_source = "<a href=\"#{quote.source_link}\" target=\"quote_extern\">#{quote.source}</a>"
    end
    ret = quote.author && quote.author.id != 0 ? quote.author.get_linked_author_name_or_blank : ""
    ret += ", " unless ret.blank? or my_source.blank?
    ret += my_source unless my_source.blank?
    ret
  end

  # returns quote with link
  def get_linked_quotation(quote)
    link_to quote.quotation, { controller: :quotations, action: :show, id: quote.id }, class: 'no-break'
  end
end

app/views/quotations/_form.html.erb
<!-- @formatter:off -->
<%#= form_with(model: quotation, url: quotation_path(quotation, locale: I18n.locale), method: :patch, local: true, html: { autocomplete: 'off' }) do |form| %>
<%= form_with(model: quotation, locale: I18n.locale, local: true, html: { autocomplete: 'off' }) do |form| %>
  <% if quotation and quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("g.error", count: quotation.errors.count) %></h2>
      <ul>
        <% quotation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quotation, label_and_description(t("g.quotes", count: 1), t(".quotation_sample")), class: "font-size-smaller" %><br/>
    <%= form.text_area :quotation, { cols: 80, rows: 2, autofocus: true } %>
  </div>

  <%= form.label :author, label_and_description(t("g.authors", count: 1), t(".author_hint")), class: "font-size-smaller" %>
  <%= render "quotations/search_author", author_id: quotation ? quotation.author_id : 0, animation: :no %>
  <%= render "quotations/search_author_results", authors: [] %>

  <div class="top_space_field">
    <%= form.label :source, label_and_description(t(".source"), t(".source_description")), class: "font-size-smaller" %><br/>
    <%= form.text_field :source, { size: 80, maxlength: 255 } %>
  </div>

  <div class="field">
    <%= form.label :source, label_and_description(t(".link"), t(".link_description")), class: "font-size-smaller" %><br/>
    <%= form.text_field :source_link, { size: 80, maxlength: 255 } %>
  </div>

  <%= render "quotations/search_category_collected",
        categories: @quotation ? @quotation.categories : nil,
        rec_ids: Category.check(@quotation),
        category_id: nil,
        category_ids: quotation ? quotation.categories.map { |c| c.id } : [] %>
  <div class="no_bottom_field">
    <%= search_field_tag :category, "", placeholder: t(".category_placeholder"), oninput: "this.form.requestSubmit()", size: 40 %>
  </div>
  <%= render "quotations/search_category_results", categories: [], rec_ids: [] %>

  <div class="top_space_field">
    <%= form.label :public, label_and_description(t("g.language")), class: "font-size-smaller" %><br/>
    <%# This is the last place where UTF-8 flags are used as emojicons and displayed as two-letter language code
        in Microsoft Windows Edge and Chrome. The reason for this is that we want to save ourselves the trouble
        of using the flags as background images and using JS in the selection.
    %>
    <%= form.select :locale, I18n.available_locales.map { |locale| [string_for_locale_utf8(locale).html_safe, locale] } %>
  </div>
  
  <% if current_user and current_user.admin == true %>
    <div class="top_space_field">
      <%= form.label :public, label_and_description(t("g.public")), class: "font-size-smaller" %><br/>
      <%= form.check_box :public %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit t("g.save") %>
    &nbsp;
    <%= link_to(image_tag("arrow_undo.png", alt: t("g.arrow_undo_alt"), title: t("g.back"), border: "0"), action: "index" ) %>
  </div>

<% end %>

app/views/quotations/_list_content.erb
<div>
  <%= form_tag('#', id: 'quotation_locales', method: :get) do |form| %>
    <% selected_locales = ((params[:locales] && params[:locales].split(',')) || []).map(&:to_sym) %>
    <% I18n.available_locales.each do |locale| %>
      <%= check_box_tag 'locales[]', locale, selected_locales.include?(locale), id: "locale_#{locale}", class: 'locale-checkbox' %>
      <%= label_tag "locale_#{locale}", string_for_locale(locale, true).html_safe %>
      &nbsp;
    <% end %>
  <% end %>
</div>

<div class="quotes-container">
  <table class="border">
    <tr>
      <th>&#127757;</th> <!-- 🌎 -->
      <th><%= t("g.quotes", count: 2) %></th>
      <th><%= image_tag("comment.png", alt: t("g.comment_alt"), title: t("g.comment", count: 2)) %></th>
      <th class="min-width-8ch"><%= t("g.actions") %></th>
    </tr>
    <%
      odd_or_even = 0
      for quotation in @quotations
        odd_or_even = 1 - odd_or_even
        number_of_comments = Comment.number_of(quotation)
    %>
        <tr valign="top" class="ListLine<%= odd_or_even %>">
          <td>
            <span class="center">
            <%= raw string_for_locale(quotation.locale) %>
          </span>
        </td>
        <td class="ListQuote">
          <span class="ListQuote"><%= h(quotation.quotation) %></span><br/>
          <%= raw_span_class_if_present("ListSource", quotation.get_author_and_source_name) %>
        </td>
        <td class="center"><%= number_of_comments if number_of_comments > 0 %></td>
        <td class="actions">
          <%= link_to image_tag("eye.png", alt: t("g.eye"), title: t("g.show"), border: 0), { action: :show, id: quotation } %>
          <% if can_edit?(quotation.user_id) %>
            <%= link_to image_tag("pencil.png", alt: t("g.pencil"), title: t("g.edit"), border: 0), action: :edit, id: quotation %>
            <% if number_of_comments == 0 %>
              <%= link_to image_tag("cancel.png", alt: t("g.red_cross"), title: t("g.delete"), border: 0),
                    { action: "destroy", id: quotation },
                    method: :delete,
                    data: { turbo_method: :delete, turbo_confirm: t(".delete", quote: truncate(quotation.quotation, length: 20)) } %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="quotes-pagination">
    <%= will_paginate @quotations %>
  </div>
</div>

<% if current_user %>
  <p class="ListNavi">
    <%= button_to t(".new"), { action: :new }, method: :get %>
  </p>
<% else %>
  <p class="opacity-50 font-size-smaller "><%= raw t(
      ".needs_login",
      login_link:
        link_to(t("layouts.application.login"), login_path(locale: I18n.locale))
    ) %></p>
<% end %>

app/views/quotations/_search_author.html.erb
<%= turbo_frame_tag :search_author do %>
  <%= hidden_field_tag "quotation[author_id]", author_id %>
  <div class="no_bottom_field">
    <%= search_field_tag :author, author_selected_name(author_id), placeholder: t(".placeholder"), oninput: "this.form.requestSubmit()", :size => 80, class: animation %>
  </div>
<% end %>

app/views/quotations/_search_author_results.html.erb
<%= turbo_frame_tag :search_author_results do %>
  <% if authors.present? and authors.count > 0 %>
    <div id="authors_list">
      <% authors.each do |author| %>
        <%= link_to author_selected_name(author.id), :controller => 'quotations', :action => 'author_selected', author_id: author  %><br />
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/quotations/_search_category_results.html.erb
<%= turbo_frame_tag :search_category_results do %>
  <% if categories.present? and categories.count > 0 %>
    <div id="categories_list">
      <% ids = category_ids.present? ? ",#{category_ids.join(',')}" : "" %>
      <% categories.each do |category| %>
        <%= link_to Category.category_or_empty(category.id), controller: :quotations, action: :category_selected, ids: "#{category.id}#{ids}-#{rec_ids.join(',')}" %><br />
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/quotations/edit.html.erb
<h1><%= t(".edit_quotation") %></h1>

<%= render 'form', quotation: @quotation %>

app/views/quotations/index.html.erb
<% pattern = h(params[:pattern]) %>
<h1><%= "#{number_with_delimiter(@quotations.total_entries)} #{t('g.quotes', count: @quotations.total_entries)}" %> <%= " #{t(".pattern", pattern: pattern)}" if pattern.present? %></h1>

<%= render :partial => 'list_content' %>

app/views/quotations/list_no_public.html.erb
<h1><%= t(".non_public_quotes") %></h1>

<%= render 'list_content' %>

app/views/quotations/new.html.erb
<h1><%= t('.new') %></h1>

<%= render 'form', quotation: @quotation %>

app/views/quotations/show.html.erb
<%
    # create a list of ordered categories with links and link titles with number of quotations
    categories = []
    @quotation.categories.i18n.order(:category).each do |r|
        categories[categories.length - 1] += ", " if categories.length > 0
        i = r.quotation_ids.size
        category = h(r.category)
        categories << link_to(category, {action: :list_by_category, category: r.id},
                        title: "#{i} #{t("g.quotes", count: i)} #{t(".of_category", category: category)}")
    end

    # link to authors detail page
    author_name = @quotation.get_author_name_or_blank
    author = link_to(h(author_name), author_path(id: @quotation.author_id),
                :title => t(".author_link", author: author_name))
    # link to authors quotes with number of quotations
    
    a = Author.find_by_id(@quotation.author_id)
    i = a.nil? ? 0 : a.quotations.size
    # only show link if we have more quotes (as the actual shown) from this author
    author_quotes = i < 2 ? "" : link_to(t(".author_quotes", count: i), {action: :list_by_author, author: @quotation.author_id},
                                   title: t(".quotes_link", count: i, author: author_name ))

    # user with links and link number of quotations in link title
    name = image_tag("#{AVATARS_URL}/#{@quotation.user_id}.png", width: "20", height: "20") + raw("&nbsp;") + hu(@quotation.user_id)
    u = User.find_by_id(@quotation.user_id)
    i = u.nil? ? 0 : u.quotations.size
    if (i >= 1)
        user = link_to(name, {action: :list_by_user, user: @quotation.user_id},
                 title: "#{i} #{t("g.quotes", count: i)} #{t(".of_user", user: name)}")
    else
        user = name
    end
%>
<h1><%=t("g.quotes", count: 1)%></h1>
<div class="flex">
  <div>
    <table id="details">
        <tr>
          <td valign=top><%= t("g.id") %>:</td>
          <td><%= raw "<span class=\"float-right\">#{string_for_locale(@quotation.locale)}</span>#{@quotation.id}" %></td>
        </tr><tr>
          <td valign=top><%= t("g.quotes", count: 1) %>:</td>
          <td><b><%= h(@quotation.quotation) %></b></td>
        </tr><tr>
          <td valign=top><%= t("g.authors", count: 1) %>:</td>
          <td><%= author %> <%= author_quotes %></td>
        </tr><tr>
          <td valign=top><%= t("quotations.form.source") %>:</td>
          <td><%= h(@quotation.source) %></td>
        </tr><tr>
          <td valign=top><%= t("quotations.form.link") %>:</td>
          <td><%= lh(@quotation.source_link) %></td>
        </tr><tr>
          <td valign=top><%= t("g.categories", count: 2) %>:</td>
          <td><%= raw categories.join %></td>
        </tr><tr>
          <td valign=top><%= t("g.created") %>:</td>
          <td><%= nice_date(@quotation.created_at) %></td>
        </tr><tr>
          <td valign=top><%= t("g.by_the_user") %>:</td>
          <td><%= user %></td>
        </tr><tr>
          <td valign=top><%= t("g.updated") %>:</td>
          <td><%= nice_date(@quotation.updated_at) %></td>
        </tr><tr>
          <td><%= t("g.public") %>:</td>
        <td><%= t("g.public_value.#{@quotation.public}") %></td>
        </tr>
    </table>
  </div>
  <% if can_edit?(@quotation.user_id) %>
    <div class="padding-left-10px">
      <%= link_to(image_tag("pencil.png", alt: t("g.pencil"), title: t("g.edit")), { action: "edit", id: @quotation.id }, { class: "no-decoration"} ) %>
    </div>
  <% end %>
</div>

<%= render partial: "comments/show" %>