config/routes.rb
Rails.application.routes.draw do
  # all joomla going now outside
  # was started from the beginning with a direct URL, e.g. "joomla" instead "start/joomla"
  get 'joomla'               => redirect(QUOTE_JOOMLA_WIKI[:de])
  get 'de/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:de])
  get 'joomla_english'       => redirect(QUOTE_JOOMLA_WIKI[:en]) # used from Joomla module, version 1.4
  get 'start/joomla_english' => redirect(QUOTE_JOOMLA_WIKI[:en]) # old page link before I18n
  get 'en/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:en])
  get 'es/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:es])
  get 'ja/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:ja])
  get 'uk/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:uk])

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: "static_pages#list"

    # static_pages controller with historical and nicer 'start' URL
    get 'start/humans'  => 'static_pages#humans'
    get 'start/contact' => 'static_pages#contact'
    get 'start/project' => 'static_pages#project'
    get 'start/use'     => 'static_pages#use'
    get 'start/help'    => 'static_pages#help'
    get 'start/list'    => 'static_pages#list'

    # dynamic generated humans.txt
    get "humans.txt" => "static_pages#humans"

    get  'categories/list_no_public'              => 'categories#list_no_public'
    get  'categories/list_by_letter/:letter'      => 'categories#list_by_letter'
    get  'categories/list_duplicates'             => 'categories#list_duplicates'
    get  'authors/list_no_public'                 => 'authors#list_no_public'
    get  'authors/list_by_letter/:letter'         => 'authors#list_by_letter'
    get  'quotations/list_no_public'              => 'quotations#list_no_public'
    get  'quotations/list_by_user/:user'          => 'quotations#list_by_user'
    get  'quotations/list_by_category/:category'  => 'quotations#list_by_category'
    get  'quotations/list_by_author/:author'      => 'quotations#list_by_author'
    post 'quotations/search_author'               => 'quotations#search_author'
    get  'quotations/author_selected/:author_id'  => 'quotations#author_selected'
    get  'quotations/category_selected/:ids'      => 'quotations#category_selected'
    get  'quotations/delete_category/(:ids)'      => 'quotations#delete_category'
    get  'comments/list_by_user/:user'            => 'comments#list_by_user'

    # Hotwire Stimulus & Hotwire Turbo
    get  'users/show_avatar'                      => 'users#show_avatar'
    get  'users/recreate_avatar'                  => 'users#recreate_avatar'
    get  'users/take_gravatar'                    => 'users#take_gravatar'
    post 'users/upload_avatar'                    => 'users#upload_avatar'

    # default controller routes
    resources :authors, :categories, :quotations
    resources :users, except: [:show, :destroy]
    resources :user_sessions, except: [:index, :show, :edit, :update]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]

    get "login"  => "user_sessions#new"
    get "logout" => "user_sessions#destroy"

    get "forbidden" => "static_pages#forbidden"
    get "not_found" => "static_pages#not_found"

    # see https://www.mintbit.com/blog/custom-404-500-error-pages-in-rails
    get "/400" => "static_pages#bad_request"
    get "/404" => "static_pages#not_found"
    get "/500" => "static_pages#internal_server"
    get "/422" => "static_pages#unprocessable"

    # catch all
    match "*path" => "static_pages#catch_all", via: :all
  end
end

app/models/category.rb
class Category < ApplicationRecord
  include ReusableMethods
  extend Mobility
  translates :category, type: :string
  belongs_to :user
  has_and_belongs_to_many :quotations
  has_many :comments, as: :commentable
  before_destroy :check_quotes_and_comments
  validate :validate_category
  after_save :expire_category_init_chars_cache
  after_destroy :expire_category_init_chars_cache

  # words, exluded from word matching without last or two last letters
  EXCLUDED_WORDS_GERMAN =
    ["ei",           # prevents "das Ei" for "ein/eine"
     "sein"].freeze  # prevents "das Sein" for "seinem/seiner/seine"
  EXCLUDED_WORDS_ENGLISH =
    ["car",          # prevents "the car" for "cards" (but also disables "cars")
     "star",         # prevents "the star" for "start" (but also disables "stars")
     "plan"].freeze  # prevents "the plan" for "plant"

  # doing Mobility case-insensitive search on category
  # returns a Category::ActiveRecord_Relation or nil
  scope :search_case_insensitive, ->(category_looking_for) do
                                    i18n do
                                      category.lower.matches("#{category_looking_for.downcase}")
                                    end
                                  end

  # count all non-public categories
  def Category.count_non_public
    return count_by_sql("select count(*) from categories where public = 0")
  end

  # gives an array with all existing categories names initial chars plus '*' if no mapping exists
  # e.g. ["a", "b", "d" ... "z", "*"]
  def Category.init_chars
    Rails.cache.fetch("category_init_chars_#{I18n.locale}", expires_in: 1.hours) do
      # Fetch all category names in the current locale
      category_names = Category.i18n.select(:category).distinct.pluck(:category)
      # Extract the initial character of each category name, map to base letter, and eliminate doubled entries
      category_names.compact.map { |category| base_letter(category[0].upcase) }.uniq
    end
  end

  # search for category with starting letters without category_ids
  # and without category_ids entries (categories already selected)
  # returns always an Category array with 0...10 entries
  def self.filter_by_category(search, category_ids)
    return [] if search.blank?

    sql = "SELECT DISTINCT c.* from categories c "
    sql << "INNER JOIN mobility_string_translations mst "
    sql << "ON c.id = mst.translatable_id "
    sql << "AND mst.translatable_type = 'Category' "
    sql << "AND mst.key = 'category' "
    sql << "AND mst.locale = '#{I18n.locale.to_s}' "
    sql << "AND mst.value LIKE '#{search}%' "
    sql << "AND mst.translatable_id NOT IN (#{category_ids.join(",")}) " if category_ids.present?
    sql << "ORDER BY mst.value LIMIT 10;"
    return Category.find_by_sql sql
  end

  # returns the category if the id is present, otherwise an empty string (e.g. id is 0 as marker for category isn't set)
  def Category.category_or_empty(id = nil)
    category = Category.find(id).category
    return category.nil? ? "" : category
  rescue
    return ""
  end

  # Build list of recommenced categories from quotation.
  #
  # quotation is Quotation object or String
  # return id list of categories found in quote
  def self.check(quotation)
    quotation = quotation.quotation if quotation.is_a?(Quotation)
    if quotation.present?
      ids_and_categories = Category.i18n.distinct.pluck(:id, :category)
      case I18n.locale
      when :ja
        ret = check_japanese(quotation, ids_and_categories)
      when :de
        ret = check_german(quotation, ids_and_categories)
      when :es
        ret = check_spanish(quotation, ids_and_categories)
      else
        ret = check_american_english(quotation, ids_and_categories)
        # if needed we can implement :uk
      end
    end
    ret.nil? ? [] : ret.uniq
  end

  # returns hash {locale => id} with identical category names
  # found in all locales for the actual @category.id
  # returns only one finding for each locale
  def self.find_duplicate_by_id(category_id)
    sql = <<-SQL
        SELECT DISTINCT t1.locale, t2.translatable_id AS t2
          FROM mobility_string_translations t1
          JOIN mobility_string_translations t2
            ON t1.value = t2.value
            AND t1.locale = t2.locale
            AND t1.locale IN ('#{I18n.available_locales.join("', '")}')
            AND t1.translatable_id <> t2.translatable_id
            AND t1.translatable_type = 'Category'
            AND t2.translatable_type = 'Category'
            AND t1.key = 'category'
            AND t2.key = 'category'
          WHERE t1.translatable_id = #{category_id};
    SQL
    result = ActiveRecord::Base.connection.execute(sql)
    duplicate = {}
    result.each do |row|
      locale = row[0]
      id = row[1]
      duplicate[locale] = id
    end
    duplicate
  end

  private

  # doing validation by own with Mobility
  # validates :category, presence: true, length: { maximum: 64 }, uniqueness: { case_sensitive: false }
  def validate_category
    current_locale = Mobility.locale.to_s
    category_in_locale = category(locale: current_locale)

    # presence validation
    if category_in_locale.blank?
      errors.add(:category, :blank)
    end

    if category_in_locale.present?
      # length validation
      if category_in_locale.length > 64
        errors.add(:category, :too_long, count: 64)
      end

      # case-insensitive uniqueness validation
      if new_record? or attribute_changed?(:category)
        already_existing = Category.search_case_insensitive(category_in_locale)
        if already_existing.present?
          errors.add(:category, :taken, value: already_existing.first.category(locale: current_locale))
        end
      end
    end
  end

  # don't delete categories with quotes or comments
  def check_quotes_and_comments
    if quotations.any?
      errors.add :base, :has_quotes
      throw :abort
    end
    if comments.any?
      errors.add :base, :has_comments
      throw :abort
    end
  end

  # delete caches for all locales if we have saved or deleted a category
  def expire_category_init_chars_cache
    I18n.available_locales.each do |locale|
      Rails.cache.delete("category_init_chars_#{I18n.locale}")
    end
  end

  # opens up the singleton class to ...
  class << self
    # ...define private class methods as only private applies to instance and not to class methods

    private

    # In Japanese, there are no spaces to separate words, so we just have to go through each character one by one.
    def check_japanese(quotation, ids_and_categories)
      # sort the list of categories for length to find e.g. "時間厳守" (punctuality) before "時間" (time)
      ids_and_categories.sort_by! { |_, category| -category.to_s.length }
      ret = []
      i = 0
      while i < quotation.length
        match_found = false
        ids_and_categories.each do |id, category|
          next if category.blank? # Skip empty or nil categories

          if quotation[i, category.length] == category
            ret << id
            i += category.length
            match_found = true
            break
          end
        end
        i += 1 unless match_found
      end
      ret
    end

    # everthing is mapped to lowercase to compare
    # even compared with one or two letters less in the ending to find e.g.
    # "Liebe" for "lieben" and "Spiel" for "spielen", but not for excluded_words
    # German Umlaut (äöü) and sharp S (ß) are mapped to find e.g. "Kampf" for "kämpfen" or "süss" for "süßer"
    def check_german(quotation, ids_and_categories)
      ret = []
      # create a lowercase list of words
      words = quotation.split(/[ ,.;\-—!?"'„”]/).map(&:downcase).reject(&:blank?)

      ids_and_categories.each do |id, category|
        next if category.blank? # Skip empty or nil categories

        category.downcase!
        category.tr!("äöü", "aou")
        category.gsub!("ß", "ss")
        words.each do |word|
          next if word.blank? # Skip empty words or punctuation marks

          word.tr!("äöü", "aou")
          word.gsub!("ß", "ss")
          # prevents e.g. "ei" for "ein"
          next if EXCLUDED_WORDS_GERMAN.include?(word.chop)
          # prevents e.g. "ei" for "eine" or "sein" for "seinem"
          next if EXCLUDED_WORDS_GERMAN.include?(word.chop.chop)

          # finds identical and also e.g. "Liebe" for "lieben" and "Spiel" for "spielen",
          ret << id if word == category || word.chop == category || word.chop.chop == category
        end
      end
      ret
    end

    # everthing is mapped to lowercase to compare
    # even compared with one or two letters less in the ending to find e.g.
    # "German" for "Germany" and "time" for "timely", but not for excluded_words
    # also tries the other way round to remove last letter from category name (if it has at least 3 chars)
    def check_american_english(quotation, ids_and_categories)
      ret = []
      # create a lowercase list of words
      words = quotation.split(/[ ,.;\-—!?"'„”]/).map(&:downcase).reject(&:blank?)

      ids_and_categories.each do |id, category|
        next if category.blank? # Skip empty or nil categories

        category.downcase!
        words.each do |word|
          next if word.blank? # Skip empty words or punctuation marks
          # prevents e.g. "plan" for "plant"
          next if EXCLUDED_WORDS_ENGLISH.include?(word.chop)
          # prevents e.g. "car" for "cards"
          next if EXCLUDED_WORDS_ENGLISH.include?(word.chop.chop)

          # finds identical and also e.g. "German" for "Germany" and "time" for "timely",
          # and the other way round "politics" for "politic"
          ret << id if word == category || word.chop == category || word.chop.chop == category ||
                       (category.size > 2 and
                        (word == category.chop || word.chop == category.chop || word.chop.chop == category.chop))
        end
      end
      ret
    end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_list_content.erb
<!-- @formatter:off -->
<%= will_paginate @categories %>

<table class="border">

  <tr>
    <th><%= raw sorted_img_if(t("g.category"), link_to(t("g.category"), controller: "categories", order: "categories"), params[:order] == "categories") %></th>
    <th><%= raw sorted_img_if(t("g.quotes", count: 2), link_to(t("g.quotes", count: 2), controller: "categories"), params[:order] != "categories") %></th>
    <th><%= image_tag("comment.png", alt: t("g.comment_alt"), title: t("g.comment", count: 2)) %></th>
    <th><%= t("g.actions") %></th>
  </tr>

  <% odd_or_even = 0
    for category in @categories
      odd_or_even = 1 - odd_or_even
      quotations = Quotation.by_category_and_locales(category.id).size
      number_of_comments = Comment.number_of(category) %>
      <tr valign="top" class="ListLine<%= odd_or_even %>">
        <td><%= raw th(category.category, 40) %></td>
        <td class="center"><%= link_to quotations.to_s, controller: "quotations", action: "list_by_category", category: category.id %></td>
        <td class="center"><%= number_of_comments if number_of_comments > 0 %></td>
        <td class="ListActions">
          <%= link_to image_tag("eye.png", alt: t("g.eye"), title: t("g.show")), locale: I18n.locale, action: "show", id: category %>
          <% if can_edit?(category.user_id) %>
            &nbsp;
            <%= link_to image_tag("pencil.png", alt: t("g.pencil"), title: t("g.edit")), locale: I18n.locale, action: "edit", id: category %>
            &nbsp;
            <% if quotations == 0 and number_of_comments == 0 %>
              <%= link_to image_tag("cancel.png", alt: t("g.red_cross"), title: t("g.delete")),  
              { locale: I18n.locale, action: "destroy", id: category },
              method: :delete,
              data: {
                turbo_method: :delete,
                turbo_confirm: t(".category_delete", category: category.category)
              } %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>

</table>

<% if current_user %>
  <p class="ListNavi">
    <%= button_to t("categories.new"), { action: :new }, method: :get %>
  </p>
<% else %>
  <p class="opacity-50 font-size-smaller "><%= raw t(".needs_login", login_link: link_to(t('layouts.application.login'), login_path(locale: I18n.locale))) %></p>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t(".edit_category") %></h1>

<%= form_with(model: @category, local: true) do |form| %>
  <% if @category and @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("g.error", count: @category.errors.count) %></h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :category, label_and_description(t("g.category"), t("categories.category_sample")), class: "font-size-smaller" %><br/>

    <div class="flex">
      <div class="field">
        <%= form.text_field "category_#{I18n.locale}", id: "category_name_#{I18n.locale}", autofocus: true, value: @category.category(locale: I18n.locale) %>
      </div>
      <div>
        <%= raw "&nbsp;#{string_for_locale(I18n.locale)}" %>
      </div>
    </div>

    <% I18n.available_locales.each do |locale| %>
        <% next if locale == I18n.locale %>
        <div class="flex opacity-50">
        <div class="field">
            <%= form.text_field "category_#{locale}", id: "category_name_#{locale}", value: @category.category(locale: locale) %>
        </div>
        <div>
            <%= raw "&nbsp;#{string_for_locale(locale)}" %>
        </div>
        </div>
      <% end %>

  <% if current_user and self.current_user.admin %>
    <div class="field">
      <%= form.label :public, label_and_description(t("g.public")), class: "font-size-smaller" %><br/>
      <%= form.check_box :public %>
    </div>
  <% end %>

 <div class="actions">
    <%= form.submit t("g.save"), name: :save %>
    &nbsp;
    <%= form.submit t("g.translate"), name: :translate %>
    &nbsp;
    <%= link_to(image_tag("arrow_undo.png", alt: t("g.arrow_undo_alt"), title: t("g.back"), border: "0"), action: :show, id: @category.id) %>
  </div>

<% end %>

app/views/categories/index.html.erb
<h1><%= "#{number_with_delimiter(@categories.total_entries)} #{t("g.categories", count: @categories.total_entries)}" %></h1>

<%= render 'list_content' %>

app/views/categories/list_by_letter.html.erb
<% headline = "#{@categories.total_entries} #{t("g.categories", count: @categories.total_entries)}"
  if params[:letter] == "*"
  	headline += " #{t(".not_starting_with_a_letter")}"
  else
  	headline += " #{t(".with_initial_letter", letter: params[:letter].first)}"
  end
%>
  <h1><%= headline %></h1>

  <%= render "list_content" %>

app/views/categories/list_duplicates.erb
<h1><%= "#{@total_count} #{t('g.duplicate', count: @total_count).capitalize}" %></h1>

<%= will_paginate @result %>
<table class="border">

  <tr>
    <th class="center"><%= t("g.locale") %></th>
    <th><%= t("g.duplicate", count: 1) %></th>
    <th><%= t("g.category") %></th>
    <th><%= t("g.category") %></th>
  </tr>

    <% @result.each do |entry| %>
      <tr>
        <td class="center"><%= raw string_for_locale(entry[0]) %></td>
        <td><%= entry[1] %></td>
        <td class="actions"><%= raw "#{entry[2]} &nbsp;
                <span class=\"float-right\">
                    #{link_to image_tag("eye.png", alt: "g.eye", title: "g.show"), action: "show", id: entry[3]}
                    #{link_to image_tag("pencil.png", alt: t("g.pencil"), title: t("g.edit")), action: "edit", id: entry[3]}
                </span>" %></td>
        <td class="actions"><%= raw "#{entry[4]} &nbsp;
                <span class=\"float-right\">
                    #{link_to image_tag("eye.png", alt: "g.eye", title: "g.show"), action: "show", id: entry[5]}
                    #{link_to image_tag("pencil.png", alt: t("g.pencil"), title: t("g.edit")), action: "edit", id: entry[5]}
                </span>" %></td>
      </tr>
    <% end %>

</table>

app/views/categories/list_no_public.html.erb
<h1><%= "#{t('g.not_publics', count: 2).capitalize} #{t('g.categories', count: 2)}" %></h1>

<%= render 'list_content' %>

app/views/categories/new.html.erb
<h1><%= t('categories.new') %></h1>

<%= form_with(model: @category, local: true) do |form| %>
  <% if @category and @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("g.error", count: @category.errors.count) %></h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category, label_and_description(t("g.category"), t("categories.category_sample")) %><br/>
    <%= form.text_field "category_#{I18n.locale}", id: "category_name_#{I18n.locale}", autofocus: true %>
  </div>

  <% if current_user and self.current_user.admin %>
    <div class="field">
      <%= form.label :public, label_and_description(t("g.public")) %><br/>
      <%= form.check_box :public %>
    </div>
  <% end %>

 <div class="actions">
    <%= form.submit t("g.save") %>
    &nbsp;
    <%= link_to(image_tag("arrow_undo.png", alt: t("g.arrow_undo_alt"), title: t("g.back"), border: "0"), action: :index) %>
  </div>

<% end %>

app/views/categories/show.html.erb
<!-- @formatter:off -->

<h1><%= t("g.category") %></h1>

<div class="flex">
  <div>
    <table id="details">
      <tr>
        <td><%= t("g.id") %>:</td>
        <td><%= h(@category.id) %></td>
      </tr>
      <% ordered_locales.each do |locale| %>
        <tr>
          <td><%= "#{t("g.name")}:" if locale == I18n.locale %></td>
          <td>
            <% if locale == I18n.locale %>
              <b><%= h(@category.category(locale: locale)) %></b>
            <% else %>
              <span class="opacity-50"><%= h(@category.category(locale: locale)) %></span>
            <% end %>

            <% if @duplicate&.key?(locale.to_s) %>
              <%= link_to(image_tag("error.png", alt: t("g.error_alt"), title: t("g.duplicate", count: 1)),
                          { action: "show", id: @duplicate[locale.to_s] },
                          { class: "no-decoration"} ) %>
            <% end %>

            <span class="float-right <%= "opacity-50" if locale != I18n.locale %>">
              <%= raw string_for_locale(locale) %>
            </span>
          </td>
        </tr>
      <% end %>
      <tr>
        <td><%= t("g.created") %>:</td>
        <td><%= nice_date @category.created_at %></td>
      </tr>
      <tr>
        <td><%= t("g.by_the_user") %>:</td>
        <td><%= image_tag("#{AVATARS_URL}/#{@category.user_id}.png", class: "avatar-small") + " " + 
                hu(@category.user_id) %></td>
      </tr>
      <% if @category.created_at != @category.updated_at %>
        <tr>
          <td><%= t("g.updated") %>:</td>
          <td><%= nice_date @category.updated_at %></td>
        </tr>
      <% end %>
      <tr>
        <td><%= t("g.public") %>:</td>
        <td><%= t("g.public_value.#{@category.public}") %></td>
      </tr>
      <tr>
        <td><%= t("g.quotes", count: @category.quotation_ids.size) %></td>
        <td><%= if @category.quotation_ids.size >= 1
            link_to(@category.quotation_ids.size.to_s, controller: "quotations", action: "list_by_category", category: @category.id)
          else
            "0"
          end %>
        </td>
      </tr>
    </table>
  </div>
  <% if can_edit?(@category.user_id) %>
    <div class="padding-left-10px">
      <%= link_to(image_tag("pencil.png", alt: t("g.pencil"), title: t("g.edit")), { action: "edit", id: @category.id }, { class: "no-decoration"} ) %>
    </div>
  <% end %>
</div>

<%= render partial: "comments/show" %>