config/routes.rb
Rails.application.routes.draw do
  # all joomla going now outside
  # was started from the beginning with a direct URL, e.g. "joomla" instead "start/joomla"
  get 'joomla'               => redirect(QUOTE_JOOMLA_WIKI[:de])
  get 'de/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:de])
  get 'joomla_english'       => redirect(QUOTE_JOOMLA_WIKI[:en]) # used from Joomla module, version 1.4
  get 'start/joomla_english' => redirect(QUOTE_JOOMLA_WIKI[:en]) # old page link before I18n
  get 'en/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:en])
  get 'es/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:es])
  get 'ja/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:ja])
  get 'uk/joomla'            => redirect(QUOTE_JOOMLA_WIKI[:uk])

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: "static_pages#list"

    # static_pages controller with historical and nicer 'start' URL
    get 'start/humans'  => 'static_pages#humans'
    get 'start/contact' => 'static_pages#contact'
    get 'start/project' => 'static_pages#project'
    get 'start/use'     => 'static_pages#use'
    get 'start/help'    => 'static_pages#help'
    get 'start/list'    => 'static_pages#list'

    # dynamic generated humans.txt
    get "humans.txt" => "static_pages#humans"

    get  'categories/list_no_public'              => 'categories#list_no_public'
    get  'categories/list_by_letter/:letter'      => 'categories#list_by_letter'
    get  'categories/list_duplicates'             => 'categories#list_duplicates'
    get  'authors/list_no_public'                 => 'authors#list_no_public'
    get  'authors/list_by_letter/:letter'         => 'authors#list_by_letter'
    get  'quotations/list_no_public'              => 'quotations#list_no_public'
    get  'quotations/list_by_user/:user'          => 'quotations#list_by_user'
    get  'quotations/list_by_category/:category'  => 'quotations#list_by_category'
    get  'quotations/list_by_author/:author'      => 'quotations#list_by_author'
    post 'quotations/search_author'               => 'quotations#search_author'
    get  'quotations/author_selected/:author_id'  => 'quotations#author_selected'
    get  'quotations/category_selected/:ids'      => 'quotations#category_selected'
    get  'quotations/delete_category/(:ids)'      => 'quotations#delete_category'
    get  'comments/list_by_user/:user'            => 'comments#list_by_user'

    # Hotwire Stimulus & Hotwire Turbo
    get  'users/show_avatar'                      => 'users#show_avatar'
    get  'users/recreate_avatar'                  => 'users#recreate_avatar'
    get  'users/take_gravatar'                    => 'users#take_gravatar'
    post 'users/upload_avatar'                    => 'users#upload_avatar'

    # default controller routes
    resources :authors, :categories, :quotations
    resources :users, except: [:show, :destroy]
    resources :user_sessions, except: [:index, :show, :edit, :update]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]

    get "login"  => "user_sessions#new"
    get "logout" => "user_sessions#destroy"

    get "forbidden" => "static_pages#forbidden"
    get "not_found" => "static_pages#not_found"

    # see https://www.mintbit.com/blog/custom-404-500-error-pages-in-rails
    get "/400" => "static_pages#bad_request"
    get "/404" => "static_pages#not_found"
    get "/500" => "static_pages#internal_server"
    get "/422" => "static_pages#unprocessable"

    # catch all
    match "*path" => "static_pages#catch_all", via: :all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale.to_s %>">
  <head>
    <title><%= page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# disable InstantClick, which is enabled by default since Turbo v8 / turbo-rails 2 %>
    <meta name="turbo-prefetch" content="false">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <%= favicon_link_tag 'apple-touch-icon.png', :rel => 'apple-touch-icon', :type => "image/png" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- ES Module Shims: Import maps polyfill for modules browsers without import maps support (Safari 16.3), see
         https://github.com/rails/importmap-rails?tab=readme-ov-file#supporting-legacy-browsers-such-as-safari-on-ios-15 -->
    <!-- <script async src="https://ga.jspm.io/npm:es-module-shims@1.8.3/dist/es-module-shims.js" data-turbo-track="reload"></script>-->
    <script async src="/javascripts/es-module-shims.js" data-turbo-track="reload"></script>
    <%= javascript_importmap_tags %>
    <%= tag.link type: 'text/plain', rel: 'author', href: '/humans.txt' %>
  </head>
  <body class="locale_<%= I18n.locale.to_s %>">
    <span id="side">
      <div id="logo_div"><a href="/<%= "#{I18n.locale}" %>"><div id="logo32"></div></a></div>
      <div id="locale">
        <span id="current-language" class="language-selector"><%= raw(string_for_locale(I18n.locale)) %> ▾ </span>
          <div id="language-dropdown" class="hidden">
            <% [:de, :en, :es, :ja, :uk].each do |locale| %>
              <%# e.g. 🇺🇦 – Українська %>
              <%= raw("<div class='language-option' data-locale='#{locale}'>#{string_for_locale(locale, false)}</div>") %>
            <% end %>
          </div>
      </div>
      <% if current_user %>
        <p>
          <% it = image_tag("#{AVATARS_URL}/#{current_user.id}.png", class: "avatar margin-bottom-4") %>
          <%= link_to(it + raw("<br />") +
                      truncate(h(current_user.login), length: 7), edit_user_path(locale: I18n.locale, id: current_user.id)) %>
          <% if current_user && current_user.super_admin? %>
            <%= raw("#{image_tag("award_star_silk_add.png", alt: t(".award_alt"), title: t(".admin"))}") %>
          <% elsif current_user && current_user.admin? %>
            <%= raw("#{image_tag("award_star_bronze_1.png", alt: t(".award_alt"), title: t(".admin"))}") %>
          <% end %>
        </p>
      <% end %>
      <div id="user_nav">
        <p><%= current_user ? link_to(t(".logout"), logout_path(locale: I18n.locale)) : link_to(t('.login'), login_path(locale: I18n.locale)) %></p>
      </div>
      <p class="<%= I18n.locale == :ja ? "margin-bottom-4" : "" %>"><%= link_to t("g.quotes", count: 0), locale: I18n.locale, controller: "quotations" %> <%= link_to("+", controller: "quotations", action: "list_no_public") if has_non_public(Quotation) %></p>
      <p class="<%= I18n.locale == :ja ? "write-vertical float-left" : "" %>" id="letter">
        <%= link_to t("g.categories", count: 0), controller: "categories" %>
        <% if current_user and current_user.admin %>
          <%= link_to("+", controller: "categories", action: "list_no_public") if has_non_public(Category) %>
      <% end %>
      </p>
      <div class="flex-center"><%= raw category_links %></div>
      <p class="<%= I18n.locale == :ja ? "write-vertical float-left" : "" %>" id="letter">
        <%= link_to t("g.authors", count: 0), controller: "authors" %> <%= link_to("+", controller: "authors", action: "list_no_public") if has_non_public(Author) %>
        <div class="flex-center"><%= raw author_links %></div>
      </p>
      <p><%= link_to t("g.help"),   locale: I18n.locale, controller: :static_pages, action: :help    %></p>
      <p><%= link_to t(".to_use"),  locale: I18n.locale, controller: :static_pages, action: :use     %></p>
      <p><%= link_to t(".project"), locale: I18n.locale, controller: :static_pages, action: :project %></p>
      <p><%= link_to t(".contact"), locale: I18n.locale, controller: :static_pages, action: :contact %></p>
      <% if current_user and current_user.admin %>
        <p>
          <%= link_to(
            image_tag("user_go.png", alt: t("g.user"), title: t("g.user")),
            { controller: :users, action: :index }) %>
          <%= link_to(
            image_tag("error.png", alt: t("g.error_alt"), title: t("g.duplicate", count: 1)),
            { controller: :categories, action: :list_duplicates }) %>
          <%= link_to(
            image_tag("comment.png", alt: t("g.comment"), title: t("g.comment", count: 2)),
            { controller: :comments, action: :index }) %>
        </p>
      <% end %>
    </span>

    <div id="content">
      <% if flash[:error] %>
        <div id="error"><%= image_tag("exclamation.png", alt: t(".exclamation_alt"), title: t(".exclamation")) %> <%= flash[:error] %></div>
      <% end %>
      <% if flash[:warning] %>
        <div id="warning"><%= image_tag("error.png", alt: t("g.error_alt"), title: t("g.warning")) %> <%= flash[:warning] %></div>
      <% end %>
      <% if flash[:notice] -%>
        <div id="notice"><%= image_tag("flag_green.png", alt: t(".green_flag_alt"), title: t(".green_flag")) %> <%= flash[:notice] %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>